PREFIX=https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/cohorts/2026/05-monitoring

.PHONY: download-dependencies
download-dependencies:
	wget -O rag_helper.py ${PREFIX}/rag_helper.py && \
		wget -O starter.py ${PREFIX}/starter.py

